test: fail_unless -> ck_assert
fail_unless macro from libcheck is deprecated.
Use new ck_assert macro.

The following warnings are reported with libcheck-0.15.2:
```
libhangul/test/test.c:450:17: warning: too many arguments for format [-Wformat-extra-args]
  450 |                 "error: next syllable: L L V V T T");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

Maybe, the commit below causes the warning:
https://github.com/libcheck/check/commit/82540c5428d3818b64d6a8aefb601e722520651f